#!/bin/sh -e

# Source debconf library.
. /usr/share/debconf/confmodule

# Decide how important it is for the user to see this message
PRIORITY=high

db_input $PRIORITY medusa/dbhost || true
db_input $PRIORITY medusa/dbport || true
db_input $PRIORITY medusa/dbusername || true
db_input $PRIORITY medusa/dbpassword || true
db_input $PRIORITY medusa/dbname || true
db_go
db_input $PRIORITY medusa/memcache || true
db_input $PRIORITY medusa/servername || true
db_go
