Document: medusa
Title: Debian medusa Manual
Author: <insert document author here>
Abstract: This manual describes what medusa is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/medusa/medusa.sgml.gz

Format: postscript
Files: /usr/share/doc/medusa/medusa.ps.gz

Format: text
Files: /usr/share/doc/medusa/medusa.text.gz

Format: HTML
Index: /usr/share/doc/medusa/html/index.html
Files: /usr/share/doc/medusa/html/*.html


