#!/bin/sh
# postinst script for medusa (dh-make-drupal)
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package

#DEBHELPER#

. /usr/share/debconf/confmodule
. /usr/share/medusa/common-functions

TMP_M4_FILE=/etc/medusa/postinst.m4.tmp
APACHE_CONF_FILE=/etc/apache2/sites-available/medusa.conf
SETTINGS_PHP=/var/www/medusa/sites/default/settings.php

case "$1" in
    configure)
        # Configure medusa
        DB_CONNECTION='pgsql://'
        # ... database username
        db_get medusa/dbusername
        if [ ! -z "${RET}" ];then
            DB_CONNECTION="${DB_CONNECTION}${RET}"
        fi
        # ... database password
        db_get medusa/dbpassword
        if [ ! -z "${RET}" ];then
            DB_CONNECTION="${DB_CONNECTION}:${RET}"
        fi
        DB_CONNECTION="${DB_CONNECTION}@"
        # ... database host
        db_get medusa/dbhost
        DB_CONNECTION="${DB_CONNECTION}${RET}"
        # ... database port
        db_get medusa/dbport
        if [ ! -z "${RET}" ];then
            DB_CONNECTION="${DB_CONNECTION}:${RET}"
        fi
        # ... database name
        db_get medusa/dbname
        DB_CONNECTION="${DB_CONNECTION}/${RET}"

        echo "<?php"                          >  $SETTINGS_PHP
        echo "\$db_url = '${DB_CONNECTION}';" >> $SETTINGS_PHP
        echo "\$db_prefix = '';"              >> $SETTINGS_PHP
        db_get medusa/servername
        echo "\$base_url = 'http://${RET}';"  >> $SETTINGS_PHP
        echo "ini_set('memory_limit', '64M');">> $SETTINGS_PHP
        echo "?>"                             >> $SETTINGS_PHP

        # create files directory
        chown -R www-data:www-data /var/lib/sitedata/medusa
        ln -f -s /var/lib/sitedata/medusa/files /var/www/drupal-site-peoplestimes-pilot/files

        # ensure cron.log exists and is www-data writable
        touch /var/log/sitelogs/medusa/cron.log
        chown www-data:www-data /var/log/sitelogs/medusa/cron.log
        # Configure apache2
        echo "changecom" > $TMP_M4_FILE
        db_get medusa/servername
        echo "define(__SERVERNAME__,${RET})dnl" >> $TMP_M4_FILE

        m4 $TMP_M4_FILE /etc/medusa/apache.conf.template > $APACHE_CONF_FILE
        ln -f -s $APACHE_CONF_FILE /etc/apache2/sites-enabled/100-medusa.conf

        rm -f $TMP_M4_FILE

        db_get medusa/serverredirects

        if [ -n "${RET}" ]; then
            echo '<VirtualHost *:80>' >> $APACHE_CONF_FILE
            echo ${RET} | perl -ne '@s = split /\s*,\s*/; print "    ServerName ", shift @s, "\n" if @s; print map { "    ServerAlias $_\n" } @s;' >> $APACHE_CONF_FILE
            db_get medusa/servername
            echo "    Redirect Permanent / http://${RET}/" >> $APACHE_CONF_FILE
            echo '</VirtualHost>' >> $APACHE_CONF_FILE
        fi

        a2enmod rewrite
        restart_apache2;

        db_get medusa/servername
        echo ""
        echo "The medua instance is now running at http://${RET}"
        echo ""
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

db_stop
exit 0
